name: Run R script daily

on:
  schedule:
    # Ogni giorno alle 08:00 UTC (09:00 in Italia d’inverno, 10:00 in estate)
    - cron: "0 8 * * *"
  workflow_dispatch:  # opzionale: per avviarlo manualmente

jobs:
  run-r:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "ggplot2", "readr"), repos="https://cloud.r-project.org")'

      - name: Run R script
        run: Rscript script.R

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: output.csv
